version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.19
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run build
          command: npm run build
      - run:
          name: Run tests with coverage
          command: npm test -- --coverage --watchAll=false --passWithNoTests
      - run:
          name: Upload coverage to Codecov
          command: |
            if [ -f coverage/lcov.info ]; then
              curl -Os https://uploader.codecov.io/latest/linux/codecov
              chmod +x codecov
              ./codecov
            fi
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_artifacts:
          path: build
          destination: build

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test